apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"web"},"name":"web","namespace":"default"},"spec":{"ports":[{"name":"web-traffic","port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"web"},"sessionAffinity":"None","type":"LoadBalancer"}}
  creationTimestamp: "2021-12-15T17:09:03Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: web
  name: web
  namespace: ingress-demo
  resourceVersion: "58860"
  selfLink: /api/v1/namespaces/ingress-demo/services/web
  uid: bd1c08ad-a17d-4db9-be5f-54583a5770cf
spec:
  clusterIP: 10.0.224.224
  externalTrafficPolicy: Cluster
  ports:
  - name: web-traffic
    nodePort: 32361
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.92.84.10
